### PR TITLE
Update Hotkey Backend

### PR DESCRIPTION
**Pull request by crizzitello**
Todo: 
  - Look into Key repeat on Linux
  - Look into Key repeat on MacOS

Done:
- Clean up related code;  Modernize C++
- Fix Windows Qt6 Hotkey broken.
- Fixed Key Repeat Issue on Windows.

### CODE REVIEW

**Comment by jrozner** [comment]
This looks like it has fixed the issue with Qt6 on windows of the event not causing the evidence capture popup but now it looks like the event is triggering twice because it pops up two dialogs rather than one.

**Comment by crizzitello** [comment]
> 

This seams to have todo with the key repeat. I have noticed if i hold the buttons down it will trigger many times.. You can get this same behavior on linux, can't really tell on mac os as i don't get a popup .

**Comment by crizzitello** [comment]
Fixed Repeat Issue on Windows;

**Comment by jrozner** [comment]
What was the fix for the event bouncing? Would you mind not force pushing so it's a little easier to see diffs across PRs? We can always squash before merge.

**Comment by jrozner** [comment]
I grabbed the build from https://github.com/theparanoids/ashirt/actions/runs/2157882178 but it doesn't seem to be fixed there. Is that the wrong build?

**Comment by crizzitello** [comment]
Yes it should be fixed (only for windows in that build) 
The [change for windows](https://github.com/theparanoids/ashirt/pull/128/files#diff-35961a38bbb89815ba466fffd058856500c4967b857d931ffcda5145f5b8aff6R75) is to add `MOD_NOREPEAT` to the modifiers According to the windows documentation:

MOD_NOREPEAT 0x4000 | Changes the hotkey behavior so that the keyboard auto-repeat does not yield multiple hotkey notifications. Windows Vista:  This flag is not supported.
-- | --

I Tested this on windows 10 And holding the key combo i only got one activation of the shortcut.

**Comment by crizzitello** [comment]
> What was the fix for the event bouncing? Would you mind not force pushing so it's a little easier to see diffs across PRs? We can always squash before merge.

**Comment by jrozner** [comment]
Installed the most recent continuous build from this pipeline and now I can't get the evidence collection popup to trigger via hotkey or the context menu from the tray icon. I'm also running into a crash when I try quitting the application from the option in the context menu.

```
0:000> k
 # Child-SP          RetAddr               Call Site
00 000000a6`0795f540 00007ff7`1a8c96c5     ashirt+0x4f584
01 000000a6`0795f570 00007fff`269f42d6     ashirt+0x696c5
02 000000a6`0795f5a0 00007fff`269f41fb     ucrtbase!<lambda_f03950bc5685219e0bcd2087efbe011e>::operator()+0xa6
03 000000a6`0795f5f0 00007fff`269f41b4     ucrtbase!__crt_seh_guarded_call<int>::operator()<<lambda_7777bce6b2f8c936911f934f8298dc43>,<lambda_f03950bc5685219e0bcd2087efbe011e> &,<lambda_3883c3dff614d5e0c5f61bb1ac94921c> >+0x3b
04 000000a6`0795f620 00007fff`26a00522     ucrtbase!execute_onexit_table+0x34
05 000000a6`0795f650 00007fff`26a004ab     ucrtbase!<lambda_ad52fe89635f51ec3b38e9c3ac6dac81>::operator()+0x4e
06 000000a6`0795f690 00007fff`26a0044e     ucrtbase!__crt_seh_guarded_call<void>::operator()<<lambda_123965863b7b46a3332720573f9ce793>,<lambda_ad52fe89635f51ec3b38e9c3ac6dac81> &,<lambda_8d528b66de6ae1e796d7f5e3101fca72> >+0x3b
07 000000a6`0795f6c0 00007ff7`1a8bf0c4     ucrtbase!common_exit+0x5e
08 000000a6`0795f710 00007fff`28467034     ashirt+0x5f0c4
09 000000a6`0795f750 00007fff`292c2651     KERNEL32!BaseThreadInitThunk+0x14
0a 000000a6`0795f780 00000000`00000000     ntdll!RtlUserThreadStart+0x21
```

**Comment by crizzitello** [comment]
That is not happening on my test machine (Win 10 20H2) The Qt6 build from https://github.com/theparanoids/ashirt/actions/runs/2162359753  is working as expected for me

**Comment by jrozner** [comment]
Just grabbed the newest build from the pipeline (https://github.com/theparanoids/ashirt/actions/runs/2164577403) for this PR and now I'm getting the dialogs popping up but I'm still getting two. Hitting the delete button also gives me a crash. It seems that the crashes are caused by the inability to connect to the api server. When I'm running the ashirt server and it's able to communicate it doesn't trigger.

Not running the server I can get the ashirt client to reliably crash on clicking the delete button for evidence or quitting the application from the context menu on the tray icon.

**Comment by crizzitello** [comment]
> Just grabbed the newest build from the pipeline (https://github.com/theparanoids/ashirt/actions/runs/2164577403) for this PR and now I'm getting the dialogs popping up but I'm still getting two. Hitting the delete button also gives me a crash. It seems that the crashes are caused by the inability to connect to the api server. When I'm running the ashirt server and it's able to communicate it doesn't trigger.
> 
> Not running the server I can get the ashirt client to reliably crash on clicking the delete button for evidence or quitting the application from the context menu on the tray icon.

That is very odd there is no code change between the previous and current run of the build. It only re ran as i accidentally closed the pr and re opening it triggers a build. I tested by both building the code locally and downloading that actions installer and using it to install ashirt.

**Comment by jrozner** [comment]
Just grabbed the newest build from this PR and I'm still seeing the same behavior. Using the hotkey I'll get 2 windows, clicking the menu entry I'll get 1. FWIW, I tried this on windows 10 yesterday and windows 11 today. Seeing the behavior on both.

**Comment by crizzitello** [comment]
Strange indeed,
Try the resulting binary when this action is finished and lmk if its any better (its built w/ Qt 6.3)  
https://github.com/crizzitello/ashirt/actions/runs/2168554112

**Review by jkennedyvz — APPROVED** [review]

**Pull request merged**
