### PR TITLE
fix Crash if manager deleted before tags fetched

### LINKED ISSUE #149: Crash on delete of evidence when tags have not yet been returned
**OS version** (`uname -a` if on a Unix-like system. For windows run `winver` and copy the text starting "Version "): win 11

**QT version** *if dynamically linking* (`qtdiag |head -n 3`): qt 6.3.0

**Description of the problem including expected versus actual behavior**: If you change the shortcut key, press the shortcut, then click delete ashirt will crash.

**Steps to reproduce**:

 1. Change shortcut key for clipboard
 2. Press new shortcut
 3. Click delete button

**Provide logs (if relevant)**:
```
 # Child-SP          RetAddr               Call Site
00 000000d2`d34fb348 00007ff6`4fbe0ebb     Qt6Core!QMimeType::staticMetaObject+0x1ffd8
01 000000d2`d34fb350 00007ff6`4fbda405     ashirt+0x50ebb
02 000000d2`d34fb380 00007fff`20bae340     ashirt+0x4a405
03 000000d2`d34fb3b0 00007fff`20bb05f4     Qt6Core!QObject::qt_static_metacall+0x17c0
04 000000d2`d34fb500 00007ff6`4fbddf70     Qt6Core!QMetaObject::activate+0x84
05 000000d2`d34fb530 00007ff6`4fbe13d9     ashirt+0x4df70
06 000000d2`d34fb570 00007ff6`4fbe0a0a     ashirt+0x513d9
07 000000d2`d34fb660 00007fff`20bae340     ashirt+0x50a0a
08 000000d2`d34fb6e0 00007fff`20bb05f4     Qt6Core!QObject::qt_static_metacall+0x17c0
09 000000d2`d34fb830 00007ff6`4fbdcaa0     Qt6Core!QMetaObject::activate+0x84
0a 000000d2`d34fb860 00007ff6`4fbe54c1     ashirt+0x4caa0
0b 000000d2`d34fb8c0 00007fff`20bae340     ashirt+0x554c1
0c 000000d2`d34fb960 00007fff`20bb05f4     Qt6Core!QObject::qt_static_metacall+0x17c0
0d 000000d2`d34fbab0 00007fff`621cba16     Qt6Core!QMetaObject::activate+0x84
0e 000000d2`d34fbae0 00007fff`621c9b06     Qt6Network!QNetworkConnectionMonitor::isMonitoring+0x8c86
0f 000000d2`d34fbb80 00007ff6`4fbac06a     Qt6Network!QNetworkConnectionMonitor::isMonitoring+0x6d76
10 000000d2`d34fbbe0 00007ff6`4fbe551e     ashirt+0x1c06a
11 000000d2`d34fbc10 00007ff6`4fbdf56d     ashirt+0x5551e
12 000000d2`d34fbc40 00007ff6`4fbd93af     ashirt+0x4f56d
13 000000d2`d34fbc70 00007ff6`4fbd95f4     ashirt+0x493af
14 000000d2`d34fbca0 00007ff6`4fbc11d8     ashirt+0x495f4
15 000000d2`d34fbcd0 00007fff`20bb6863     ashirt+0x311d8
16 000000d2`d34fbd00 00007fff`23affc36     Qt6Core!QObject::event+0xd3
17 000000d2`d34fbf20 00007fff`23ac2f6e     Qt6Widgets!QWidget::event+0xe76
18 000000d2`d34fc000 00007fff`23ac1f9f     Qt6Widgets!QApplicationPrivate::notify_helper+0x10e
19 000000d2`d34fc030 00007fff`20b734e5     Qt6Widgets!QApplication::notify+0x187f
1a 000000d2`d34fc500 00007fff`20b75d3f     Qt6Core!QCoreApplication::notifyInternal2+0xc5
1b 000000d2`d34fc570 00007fff`23690f6f     Qt6Core!QCoreApplicationPrivate::sendPostedEvents+0x21f
1c 000000d2`d34fc650 00007fff`20cceda0     Qt6Gui!QWindowsGuiEventDispatcher::sendPostedEvents+0xf
1d 000000d2`d34fc680 00007fff`23690f49     Qt6Core!QEventDispatcherWin32::processEvents+0x90
1e 000000d2`d34ff7e0 00007fff`20b78bef     Qt6Gui!QWindowsGuiEventDispatcher::processEvents+0x19
1f 000000d2`d34ff810 00007fff`20b712fd     Qt6Core!QEventLoop::exec+0x19f
20 000000d2`d34ff8b0 00007ff6`4fb9baa2     Qt6Core!QCoreApplication::exec+0x15d
21 000000d2`d34ff910 00007ff6`4fbee3a7     ashirt+0xbaa2
22 000000d2`d34ffb00 00007ff6`4fbd7bb2     ashirt+0x5e3a7
23 000000d2`d34ffb90 00007fff`9efd54e0     ashirt+0x47bb2
24 000000d2`d34ffbd0 00007fff`9fbc485b     KERNEL32!BaseThreadInitThunk+0x10
25 000000d2`d34ffc00 00000000`00000000     ntdll!RtlUserThreadStart+0x2b
```

### PR DESCRIPTION
**Pull request by crizzitello**
Clean up the TagEditor
Fix #149

### CODE REVIEW

**Comment by jrozner** [comment]
I don't see anything actually modifying getTagsReply. The only place it's ever referenced is the line where it's initialized to nullptr. Did we forget to connect it up?

**Comment by crizzitello** [comment]
> I don't see anything actually modifying getTagsReply. The only place it's ever referenced is the line where it's initialized to nullptr. Did we forget to connect it up?

Yes and lets in that case use this PR to clean up this widget

**Comment by jrozner** [comment]
Sounds good. The reason I went looking was I was curious if we were going to run into a race condition with this. Is Qt inherently threaded or any of the networking code?

**Review by jrozner — APPROVED** [review]
Change looks good. It's no longer crashing.

**Pull request merged**
