### PR TITLE
prevent hotkeys from firing when settings menu is open

### LINKED ISSUE #87: Prevent hotkeys on settings menu
**OS version** (`uname -a` if on a Unix-like system. For windows run `winver` and copy the text starting "Version "):
darwin
**QT version** *if dynamically linking* (`qtdiag |head -n 3`):
5.15.2

**Description of the problem including expected versus actual behavior**:
If you attempt to enter a hotkey combination in the settings menu that is already being used by ashirt, it will not be entered and the application will trigger a screenshot.

**Steps to reproduce**:
set window hotkey: ctrl+meta+3
set area hotkey: ctrl+meta+4
save settings
attempt to set window hotkey again to ctrl+meta+3, or swap to ctrl+meta+4.

### PR DESCRIPTION
**Pull request by JoelAtDeluxe**
This PR prevents the hotkeys from working whenever the settings menu is open. 

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Comment by jkennedyvz** [comment]
@JoelAtDeluxe This doesn't seem to work for me on MacOs. I also noticed that there is no way to "clear" the shortcut settings within the application. If you click a shortcut box, it blanks the value for the new prompt. If you do not enter a hotkey, and click save, there is no value present in the settings page, but the hotkey is still registered and functioning.

**Comment by jkennedyvz** [comment]
** The blanked settings do remove the hotkey bindings if ashirt is closed and reopened.

**Comment by JoelAtDeluxe** [comment]
That's odd. This could be an issue with how hot keys work in the library. I'll double check that the unregister actually does something meaningful in the library.

With regards to clearing, there's no good way to clear this field while in the settings. Should I just put a "clear" button next to each hot key?

**Comment by JoelAtDeluxe** [comment]
For the hot keys not disabling: we use the function `unregisterAllHotkeys` when we enter this page. That's defined for linux and windows, but notably, not for mac. :( It should be  an easy fix, but I obviously need to play with this on a mac to make sure it's correct.

**Review by jkennedyvz — APPROVED** [review]

**Pull request merged**
