### PR TITLE
Change bundle to com.theparanoids.ashirt

### PR DESCRIPTION
**Pull request by jkennedyvz**
This PR changes the application bundle id to com.theparanoids.ashirt to prepare for signing and notarization.

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Comment by jrozner** [comment]
Is this going to impact the path in `$HOME/Library/Preferences` or `$HOME/Library/Application Support` where the files are saved and is this specifically for MacOS packaging? Not specifically related but for #69 we might want to look into migrating away from using the automatic bundle packages that qmake provides us and instead handle it manually with qtmacdeploy. It's unclear how much of that is going to be migrated over to cmake and to do all the fancy backgrounds and stuff we end up having to repackage the app bundle anyway it looks like.

**Comment by jkennedyvz** [comment]
> Is this going to impact the path in `$HOME/Library/Preferences` or `$HOME/Library/Application Support` where the files are saved and is this specifically for MacOS packaging?

This change should only modify the ID in the application plist. Currently this id is `com.yourcompany.ashirt` and storage under the folders mentioned is just ./ashirt/ so I do not think this changes those directories.



> Not specifically related but for #69 we might want to look into migrating away from using the automatic bundle packages that qmake provides us and instead handle it manually with qtmacdeploy. It's unclear how much of that is going to be migrated over to cmake and to do all the fancy backgrounds and stuff we end up having to repackage the app bundle anyway it looks like.

Agreed here, this is something that will need to be updated when we migrate to cmake.

**Comment by jkennedyvz** [comment]
This PR will be closed when #76 is merged

**Comment by jkennedyvz** [comment]
#76 merged

**Pull request closed without merging**
