### PR TITLE
Always make the icon a mask

### PR DESCRIPTION
**Pull request by jrozner**
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Comment by crizzitello** [comment]
Rebase on main to fix the Mac OS build.

**Comment by jrozner** [comment]
This ended up not working. @crizzitello I went to #qt on irc asking for advice but wasn't able to get any. It seems like the masking support specifically doesn't work on windows. Not sure about linux yet. Looking for ways to handle inverting the colors depending on whether the bar is light or dark. Any thoughts on a way to do that without having to poll for changes to the OS theme or do theming within qt?

**Comment by crizzitello** [comment]
> This ended up not working. @crizzitello I went to #qt on irc asking for advice but wasn't able to get any. It seems like the masking support specifically doesn't work on windows. Not sure about linux yet. Looking for ways to handle inverting the colors depending on whether the bar is light or dark. Any thoughts on a way to do that without having to poll for changes to the OS theme or do theming within qt?

Yes I know of a way to do this by using the font color. We will need to land #137  to fix the lack of signing on other repos / local builds

**Comment by jrozner** [comment]
Closing because #138 superceeds this

**Pull request closed without merging**
