### PR TITLE
Update GitHub Actions Workflow

### LINKED ISSUE #214: Update set-output in actions
Currently we're using the old style ::set-output directives to store state in the environment. This is deprecated and we need to move to the new style. More information is available https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

### LINKED ISSUE #215: Cached action isn't setup correctly
Getting errors in the actions that the key `cached` isn't correct. It's probably supposed to be `cache`. Check out how to properly set this up and determine if we actually care about it.

### PR DESCRIPTION
**Pull request by timobrembeck**
- Update set-output in actions (fixes #214)
- Use correct config key in GitHub cache action (fixes #215)

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

Thanks a lot in advance for your feedback!

### CODE REVIEW

**Comment by jrozner** [comment]
Running the action right now. The changes look good and correct. Thanks!

**Comment by timobrembeck** [comment]
Hmm, apparently there is a deeper problem with caching which was undetected before because the `cache` key is `false` by default...

My initial impression was that maybe the cached version is somehow outdated or incompatible with a newer Python version released in the meantime, so I thought incrementing the key could help.

However, the error message also states:

> You have discovered a bug in aqt.

<details>
  <summary>Traceback</summary>

   ```
Symlink loop from '/opt/Qt/6.4.0/gcc_64/lib/libQt6Sql.so.6'
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.1/x64/lib/python3.11/pathlib.py", line 1003, in resolve
    p.stat()
  File "/opt/hostedtoolcache/Python/3.11.1/x64/lib/python3.11/pathlib.py", line 1013, in stat
    return os.stat(self, follow_symlinks=follow_symlinks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 40] Too many levels of symbolic links: '/opt/Qt/6.4.0/gcc_64/lib/libQt6Sql.so.6'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.1/x64/lib/python3.11/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.1/x64/lib/python3.11/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.1/x64/lib/python3.11/site-packages/aqt/installer.py", line 893, in installer
    szf.extractall(path=base_dir)
  File "/opt/hostedtoolcache/Python/3.11.1/x64/lib/python3.11/site-packages/py7zr/py7zr.py", line 955, in extractall
    self._extract(path=path, return_dict=False, callback=callback)
  File "/opt/hostedtoolcache/Python/3.11.1/x64/lib/python3.11/site-packages/py7zr/py7zr.py", line 625, in _extract
    sym_dst = t.resolve()
              ^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.1/x64/lib/python3.11/pathlib.py", line 1005, in resolve
    check_eloop(e)
  File "/opt/hostedtoolcache/Python/3.11.1/x64/lib/python3.11/pathlib.py", line 990, in check_eloop
    raise RuntimeError("Symlink loop from %r" % e.filename)
RuntimeError: Symlink loop from '/opt/Qt/6.4.0/gcc_64/lib/libQt6Sql.so.6'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.1/x64/lib/python3.11/site-packages/aqt/installer.py", line 99, in run
    args.func(args)
  File "/opt/hostedtoolcache/Python/3.11.1/x64/lib/python3.11/site-packages/aqt/installer.py", line 294, in run_install_qt
    run_installer(qt_archives.get_packages(), base_dir, sevenzip, keep)
  File "/opt/hostedtoolcache/Python/3.11.1/x64/lib/python3.11/site-packages/aqt/installer.py", line 835, in run_installer
    pool.starmap(installer, tasks)
  File "/opt/hostedtoolcache/Python/3.11.1/x64/lib/python3.11/multiprocessing/pool.py", line 375, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.1/x64/lib/python3.11/multiprocessing/pool.py", line 774, in get
    raise self._value
RuntimeError: Symlink loop from '/opt/Qt/6.4.0/gcc_64/lib/libQt6Sql.so.6'
Arguments: `['/opt/hostedtoolcache/Python/3.11.1/x64/lib/python3.11/site-packages/aqt/__main__.py', 'install-qt', 'linux', 'desktop', '6.4.0', '--outputdir', '/opt/Qt']` Host: `uname_result(system='Linux', node='fv-az989-459', release='5.15.0-1031-azure', version='#38~20.04.1-Ubuntu SMP Mon Jan 9 18:23:48 UTC 2023', machine='x86_64')`
===========================PLEASE FILE A BUG REPORT===========================
You have discovered a bug in aqt.
Please file a bug report at https://github.com/miurahr/aqtinstall/issues.
Please remember to include a copy of this program's output in your report.
Exception in thread Thread-1 (_monitor):
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.1/x64/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
Exception ignored in: <function Pool.__del__ at 0x7fd3ae01f240>
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.1/x64/lib/python3.11/multiprocessing/pool.py", line 271, in __del__
    self._change_notifier.put(None)
  File "/opt/hostedtoolcache/Python/3.11.1/x64/lib/python3.11/multiprocessing/queues.py", line 377, in put
    self._writer.send_bytes(obj)
  File "/opt/hostedtoolcache/Python/3.11.1/x64/lib/python3.11/multiprocessing/connection.py", line 199, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/opt/hostedtoolcache/Python/3.11.1/x64/lib/python3.11/multiprocessing/connection.py", line 410, in _send_bytes
    self._send(header + buf)
  File "/opt/hostedtoolcache/Python/3.11.1/x64/lib/python3.11/multiprocessing/connection.py", line 367, in _send
    n = write(self._handle, buf)
        ^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 9] Bad file descriptor
Error: Error: The process '/opt/hostedtoolcache/Python/3.11.1/x64/bin/python3' failed with exit code 1
   ```

</details>

Should I open an issue in https://github.com/miurahr/aqtinstall/issues as suggested in the error log? Could this be related to https://github.com/miurahr/aqtinstall/issues/224?

**Comment by jrozner** [comment]
Ya, maybe open an issue with them. We can also try bumping the version of Qt to 6.4.2 and maybe something about it changed that fixed it. Other thing we do is maybe just remove the caching action all together until we can get it working later. It's not like it's been working up until this point so we're not going to have any loss there.

**Comment by jrozner** [comment]
Do we know why this succeeded now but didn't before?

**Comment by timobrembeck** [comment]
> Do we know why this succeeded now but didn't before?

Yes, incrementing the cache key in 646749b0a628bd188f6a8938d59c72bd1bcd4898 invalidated the cache, meaning the caching action did nothing (like before) and the installation succeeded. Would be interesting if the workflow succeeds again, with the new cache restored...

**Comment by jrozner** [comment]
That makes sense. I'm re-running the job now to see if it succeeds

**Comment by timobrembeck** [comment]
> That makes sense. I'm re-running the job now to see if it succeeds

Seems like it :+1:

So then I would blame the newer Python version and I guess this problem will only re-occur when the action runner image updates its Python version without a changed cache key (which would then require it to update `v1` to `v2` in case that happens)... not sure if it's possible to include the Python version (including the minor tag) of the current image in the cache key as well.

**Comment by timobrembeck** [comment]
> Seems like it :+1:

Well, did it? After having force-pushed the branch to clean up the git history, I'm a little bit confused now which of these workflow runs was the critical :thinking: 

- https://github.com/theparanoids/ashirt/actions/runs/4049472317
- https://github.com/theparanoids/ashirt/actions/runs/4066943697

Sorry, could you approve the workflow again?

**Comment by jrozner** [comment]
Just ran it again

**Comment by timobrembeck** [comment]
Hmm ok, obviously the problem persists. So I removed the GitHub cache action for the time being, since I don't have any other ideas how to fix it.

**Review by jrozner — APPROVED** [review]
Looks good. We can revisit caching at a later time or just forget about it since it doesn't seem to have worked in the past anyway

**Pull request merged**
