### PR TITLE
Add ability to check for updates

### LINKED ISSUE #40: Notify user of new version available
Due to potential complexity and differences between platforms automatic updates may not be trivial and may require extra work. This is especially true on macos where screen recording permissions need to be reset. A good first step is simply notifying a user that there is a newer version available and directing the user to the releases page on GitHub.

### PR DESCRIPTION
**Pull request by JoelAtDeluxe**
This PR adds in a daily version check, notifying the user if an update is available for the application, along with what level of upgrade is available (patch, minor, and major releases). This relies on proper semver tagging. If the semver tags are not present, then the application will not notify the user of any upgrades, due to the system not really knowing that an upgrade is available.

Addresses Issue: #40 

Note: some of this logic relies on a proper tag and repository environment variables to be present when building the application. 

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Comment by jkennedyvz** [comment]
Hi Joel,

Could you please include updates to [Readme_Developer](https://github.com/theparanoids/ashirt/blob/master/Readme_Developer.md) that describe the tag and repository environment variables for building?

**Comment by JoelAtDeluxe** [comment]
Good idea. I'll work on that next.

**Comment by jrozner** [comment]
Haven't quite gotten this working yet. I've added a v1.0.0 pre-release release to the project to test against and am running local builds with the following environment variables set:

```
export GITHUB_SHA="f0682e37"
export GITHUB_REF="tags/v0.9.9"
export GITHUB_REPOSITORY="theparanoids/ashirt"
```

When running the application from the terminal the debug message `Skipping release check: no owner or repo set.` is printed.

**Comment by jrozner** [comment]
Functionality seems good and verified that this is all working. Can we update the text of the notification toaster to read "A new version is available! Click here to download vx.x.x" and instead of popping up the about dialog open the url for the download in their browser? Not sure how much control we have over that but it's it not possible that's totally fine.

If we're going to stay with the notification in the about dialog we should probably bring the update notification up higher in the about dialog. Can we remove it from the rendered markdown and instead have like an optional (only when an update is available) text label above the the markdown rendering text area that says the above text that I wrote for the toaster? Just "here" should be a hyperlink to the download.

**Comment by JoelAtDeluxe** [comment]
I'll look into opening the page on their browser. I'd say the challenge with selecting a version for the user is that a new major revision could be incompatible with the server. But, I suppose the alternative is that we require each user to grok semantic versioning, which is really no better.

**Review by jrozner — APPROVED** [review]

**Pull request merged**
